POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email" : "kenny@email.com",
    "password" : "password"
}

###

POST http://localhost:3000/post
Authorization: Bearer bGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imtlbm55QGVtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcyMTczMzI5M30.MqZb0L5u4Rn7Hceq0yNLgEWp_wgm5-ejfm6lae7kGZk
Content-Type: application/json

